export const CR06_INDEX={LEFT_SHOULDER:11,RIGHT_SHOULDER:12,LEFT_HIP:23,RIGHT_HIP:24,LEFT_KNEE:25,RIGHT_KNEE:26,LEFT_ANKLE:27,RIGHT_ANKLE:28};
export const CR06_REQUIRED_LANDMARKS=Object.values(CR06_INDEX);
export const CR06_THRESHOLDS={MIN_VISIBILITY:.45,TAP_DISPLACEMENT_MIN_RATIO:.13,RETURN_DISPLACEMENT_MAX_RATIO:.055,KNEE_ANGLE_MIN_DEG:65,KNEE_ANGLE_MAX_DEG:120,HIP_TILT_MAX_DEG:9,SIMULTANEOUS_MOVE_RATIO:.10,MIN_REP_DURATION_MS:800,MAX_REP_DURATION_MS:5000,MAX_FRAME_GAP_MS:1000};
export const CR06_ANALYSIS_MODE="mediapipe_cr06_alternating_heel_tap";export const DEFAULT_CR06_REWARD_XP=30;
