import {UPPER_LIMB_THRESHOLDS as T} from "./constants.js";
export function createUpperLimbSession(profile,config={}){
 const t=config.thresholds||T,target=Math.max(1,Number(config.targetReps)||profile.targetReps||1);let base=null,phase="calibrating",side=null,start=0,reps=[],left=0,right=0,drift=0,tilt=0,lean=0,fast=0,bent=0,feet=0,tracking=0,ready=false,lastEvent={};
 const event=(k,n)=>{if(n-(lastEvent[k]??-Infinity)>t.EVENT_COOLDOWN_MS){lastEvent[k]=n;return true}return false};
 const summary=()=>({totalReps:reps.length,targetReps:target,leftReps:left,rightReps:right,validReps:reps.filter(r=>!r.issues.length).length,elbowDriftCount:drift,tiltCount:tilt,trunkLeanCount:lean,tooFastCount:fast,bentElbowCount:bent,footMoveCount:feet,trackingInterruptionCount:tracking,repRecords:reps.slice(),phase,completed:reps.length>=target});
 function processFrame(f){const now=f.timestamp||0;if(!f.bodyReady){if(ready)tracking++;ready=false;return{summary:summary(),feedback:"請保持上半身、雙手與雙腳完整入鏡"}}ready=true;if(!base){base={...f};phase="ready";return{summary:summary(),feedback:"起始姿勢已建立，可以開始"};}
  const lEl=f.leftElbowAngle??180,rEl=f.rightElbowAngle??180,lSh=f.leftShoulderAngle??0,rSh=f.rightShoulderAngle??0,badTilt=f.shoulderTiltDeg>t.TILT_MAX_DEG||f.pelvisTiltDeg>t.TILT_MAX_DEG,badLean=f.trunkLeanDeg>t.TRUNK_LEAN_MAX_DEG,footMove=Math.max(Math.abs(f.leftAnkleX-base.leftAnkleX),Math.abs(f.rightAnkleX-base.rightAnkleX),Math.abs(f.leftAnkleY-base.leftAnkleY),Math.abs(f.rightAnkleY-base.rightAnkleY))/f.bodyScale>t.FOOT_MOVE_RATIO;
  let value=0,returning=false,currentSide=null;
  if(profile.mode==="elbow_cycle"){value=Math.min(lEl,rEl);currentSide=lEl<=rEl?"left":"right";if(phase==="ready"&&value<=t.ELBOW_FLEXED_DEG){phase="out";side=currentSide;start=now}returning=phase==="out"&&(side==="left"?lEl:rEl)>=t.ELBOW_EXTENDED_DEG;}
  else if(profile.mode==="elbow_extension"){value=Math.max(lEl,rEl);currentSide=lEl>=rEl?"left":"right";if(phase==="ready"&&value>=t.ELBOW_EXTENDED_DEG){phase="out";side=currentSide;start=now}returning=phase==="out"&&(side==="left"?lEl:rEl)<=110;}
  else if(profile.mode==="shoulder_raise"){value=Math.max(lSh,rSh);currentSide=lSh>=rSh?"left":"right";if(phase==="ready"&&value>=t.SHOULDER_TARGET_DEG){phase="out";side=currentSide;start=now}returning=phase==="out"&&(side==="left"?lSh:rSh)<=t.SHOULDER_START_DEG;}
  else if(profile.mode==="external_rotation"){value=f.wristSeparation-base.wristSeparation;if(phase==="ready"&&value>=t.ROTATION_TARGET_RATIO){phase="out";side="both";start=now}returning=phase==="out"&&value<=t.ROTATION_START_RATIO;}
  else {const dl=(base.leftWristX-f.leftWristX)/f.bodyScale,dr=(f.rightWristX-base.rightWristX)/f.bodyScale;value=Math.max(dl,dr);currentSide=dl>=dr?"left":"right";if(phase==="ready"&&value>=t.REACH_TARGET_RATIO){phase="out";side=currentSide;start=now}returning=phase==="out"&&value<=t.RETURN_RATIO;}
  if(returning){const durationMs=now-start,issues=[];const elbowDrift=Math.max(f.leftElbowDrift-base.leftElbowDrift,f.rightElbowDrift-base.rightElbowDrift)>t.ELBOW_DRIFT_RATIO;if(elbowDrift){issues.push("drift");drift++;}if(badTilt){issues.push("tilt");tilt++;}if(badLean){issues.push("lean");lean++;}if(durationMs<t.TOO_FAST_MS){issues.push("fast");fast++;}if(profile.mode==="shoulder_raise"&&Math.min(lEl,rEl)<t.ELBOW_STRAIGHT_MIN_DEG){issues.push("bent");bent++;}if(profile.mode==="lateral_reach"&&footMove){issues.push("feet");feet++;}let rep=null;if(durationMs>=t.MIN_REP_MS&&durationMs<=t.MAX_REP_MS){rep={side,durationMs,issues};reps.push(rep);if(side==="left")left++;else if(side==="right")right++;else{left++;right++;}}phase="ready";side=null;return{summary:summary(),completedRep:rep,feedback:issues.length?"完成一次，請依提醒調整":"很好，動作與回位控制穩定"};}
  const feedback=footMove&&profile.mode==="lateral_reach"?"雙腳請固定，不可跨步":badLean?"保持軀幹直立，不要借力":badTilt?"肩膀與骨盆保持穩定":phase==="out"?"慢慢控制回到起始位置":"依說明完成抬起或伸取";return{summary:summary(),feedback};
 }return{processFrame,getSummary:summary};
}
