const P = { LEFT_SHOULDER:11, RIGHT_SHOULDER:12, LEFT_HIP:23, RIGHT_HIP:24, LEFT_KNEE:25, RIGHT_KNEE:26, LEFT_ANKLE:27, RIGHT_ANKLE:28 };

export const LE02_REQUIRED_LANDMARKS = [
  P.LEFT_SHOULDER, P.RIGHT_SHOULDER, P.LEFT_HIP, P.RIGHT_HIP,
  P.LEFT_KNEE, P.RIGHT_KNEE, P.LEFT_ANKLE, P.RIGHT_ANKLE,
];

export const LE02_THRESHOLDS = {
  MIN_VISIBILITY: 0.5,
  REP_START_HIP_ANGLE_MAX_DEG: 165,
  TOP_CANDIDATE_HIP_ANGLE_MAX_DEG: 145,
  TARGET_HIP_ANGLE_MAX_DEG: 140,
  EXCESSIVE_RAISE_HIP_ANGLE_MAX_DEG: 105,
  NEUTRAL_HIP_ANGLE_MIN_DEG: 165,
  KNEE_EXTENSION_MIN_DEG: 165,
  BODY_ROLL_MAX_DEG: 10,
  TOP_CONFIRM_FRAMES: 2,
  NEUTRAL_CONFIRM_FRAMES: 3,
  MIN_REP_DURATION_MS: 1200,
  MAX_REP_DURATION_MS: 8000,
  TOO_FAST_DURATION_MS: 1800,
  MAX_FRAME_GAP_MS: 700,
};

export const LE02_ANALYSIS_MODE = "mediapipe_le02_straight_leg_raise";
export const DEFAULT_LE02_REWARD_XP = 30;
