export const CR03_INDEX={LEFT_SHOULDER:11,RIGHT_SHOULDER:12,LEFT_HIP:23,RIGHT_HIP:24,LEFT_KNEE:25,RIGHT_KNEE:26,LEFT_ANKLE:27,RIGHT_ANKLE:28};
export const CR03_REQUIRED_LANDMARKS=Object.values(CR03_INDEX);
export const CR03_THRESHOLDS={MIN_VISIBILITY:.45,TILT_DELTA_MIN_DEG:5,RETURN_DELTA_MAX_DEG:2.5,EXCESSIVE_TILT_DEG:18,HIP_LIFT_MAX_RATIO:.10,KNEE_MOVEMENT_MAX_RATIO:.12,MIN_REP_DURATION_MS:1200,MAX_REP_DURATION_MS:7000,MAX_FRAME_GAP_MS:1000};
export const CR03_ANALYSIS_MODE="mediapipe_cr03_pelvic_tilt";export const DEFAULT_CR03_REWARD_XP=30;
