export const CR08_INDEX={LEFT_SHOULDER:11,RIGHT_SHOULDER:12,LEFT_WRIST:15,RIGHT_WRIST:16,LEFT_HIP:23,RIGHT_HIP:24,LEFT_KNEE:25,RIGHT_KNEE:26,LEFT_ANKLE:27,RIGHT_ANKLE:28};
export const CR08_REQUIRED_LANDMARKS=Object.values(CR08_INDEX);
export const CR08_THRESHOLDS={MIN_VISIBILITY:.5,HOLD_DURATION_MS:6000,REST_DURATION_MS:1200,SHOULDER_HIP_SKEW_MAX_DEG:9,TRUNK_LEAN_MAX_DEG:9,ROTATION_WIDTH_CHANGE_MAX_RATIO:.16,CENTER_SHIFT_MAX_RATIO:.09,HAND_MOVEMENT_MAX_RATIO:.10,MAX_FRAME_GAP_MS:1000};
export const CR08_ANALYSIS_MODE="mediapipe_cr08_standing_anti_rotation";export const DEFAULT_CR08_REWARD_XP=30;
