export const SH02_INDEX={LEFT_SHOULDER:11,RIGHT_SHOULDER:12,LEFT_ELBOW:13,RIGHT_ELBOW:14,LEFT_WRIST:15,RIGHT_WRIST:16,LEFT_HIP:23,RIGHT_HIP:24};
const P=SH02_INDEX;export const SH02_REQUIRED_LANDMARKS=Object.values(P);
export const SH02_THRESHOLDS={MIN_VISIBILITY:.5,HOLD_DURATION_MS:6000,REST_DURATION_MS:1200,ELBOW_ANGLE_MIN:80,ELBOW_ANGLE_MAX:100,ELBOW_TORSO_MAX_RATIO:.22,WRIST_MOVEMENT_MAX_RATIO:.07,TORSO_ROTATION_MAX_DEG:10,SHRUG_MAX_RATIO:.055,MAX_FRAME_GAP_MS:1000};
export const SH02_ANALYSIS_MODE="mediapipe_sh02_external_rotation_isometric";export const DEFAULT_SH02_REWARD_XP=30;
