export const SH04_INDEX={LEFT_SHOULDER:11,RIGHT_SHOULDER:12,LEFT_ELBOW:13,RIGHT_ELBOW:14,LEFT_WRIST:15,RIGHT_WRIST:16,LEFT_HIP:23,RIGHT_HIP:24};
export const SH04_REQUIRED_LANDMARKS=Object.values(SH04_INDEX);
export const SH04_THRESHOLDS={MIN_VISIBILITY:.5,HOLD_DURATION_MS:6000,REST_DURATION_MS:1200,ABDUCTION_MAX_DEG:8,ARM_MOVEMENT_MAX_RATIO:.07,SHRUG_MAX_RATIO:.055,TRUNK_SIDE_BEND_MAX_DEG:8,HIP_TILT_MAX_DEG:7,MAX_FRAME_GAP_MS:1000};
export const SH04_ANALYSIS_MODE="mediapipe_sh04_abduction_isometric";export const DEFAULT_SH04_REWARD_XP=30;
