import assert from "node:assert/strict";
import{createBedsideSitUpSession}from"../js/ai/exercises/bedsideSitUp/session.js";
import{calculateBedsideSitUpScore}from"../js/ai/exercises/bedsideSitUp/score.js";
const session=createBedsideSitUpSession({targetReps:1});
const frame=(timestamp,torsoAngleDeg,legDropRatio)=>({timestamp,bodyReady:true,torsoAngleDeg,legDropRatio,leftElbowAngle:120,rightElbowAngle:125});
session.processFrame(frame(0,10,0));
session.processFrame(frame(100,35,0));
session.processFrame(frame(700,55,.05));
session.processFrame(frame(1300,62,.2));
session.processFrame(frame(1400,75,.22));
session.processFrame(frame(1500,78,.24));
session.processFrame(frame(1600,80,.25));
session.processFrame(frame(1700,80,.25));
const result=session.processFrame(frame(2100,12,0));
assert.equal(result.summary.totalReps,1);
assert.equal(result.summary.validReps,1);
assert.equal(result.summary.completed,true);
assert.ok(calculateBedsideSitUpScore(result.summary).score>=90);
console.log("AD02 bedside-sit-up session tests passed");
