export const HP06_INDEX={LEFT_SHOULDER:11,RIGHT_SHOULDER:12,LEFT_HIP:23,RIGHT_HIP:24,LEFT_KNEE:25,RIGHT_KNEE:26,LEFT_ANKLE:27,RIGHT_ANKLE:28};const P=HP06_INDEX;
export const HP06_REQUIRED_LANDMARKS=Object.values(P);
export const HP06_THRESHOLDS={MIN_VISIBILITY:.5,OPEN_START_RATIO:.055,OPEN_TOP_RATIO:.1,TARGET_OPEN_RATIO:.12,EXCESSIVE_OPEN_RATIO:.3,RETURN_RATIO:.035,FEET_SEPARATION_MAX_RATIO:.08,KNEE_FLEXION_MIN_DEG:75,KNEE_FLEXION_MAX_DEG:105,BODY_ROLL_MAX_DEG:8,TOP_CONFIRM_FRAMES:2,RETURN_CONFIRM_FRAMES:3,MIN_REP_DURATION_MS:1200,MAX_REP_DURATION_MS:8000,TOO_FAST_MS:1800};
export const HP06_ANALYSIS_MODE="mediapipe_hp06_clamshell";export const DEFAULT_HP06_REWARD_XP=30;
