export const HP09_REQUIRED_LANDMARKS=[11,12,23,24,25,26,27,28];
export const HP09_THRESHOLDS={MIN_VISIBILITY:.5,STEP_DISPLACEMENT_MIN_RATIO:.22,FOLLOW_DISPLACEMENT_MIN_RATIO:.14,STANCE_WIDTH_RETURN_TOLERANCE_RATIO:.25,TARGET_STEP_MIN_RATIO:.2,TARGET_STEP_MAX_RATIO:.8,EXCESSIVE_STEP_RATIO:1.0,KNEE_ANGLE_MIN_DEG:140,KNEE_ANGLE_MAX_DEG:175,HIP_FLEXION_MIN_DEG:8,HIP_FLEXION_MAX_DEG:40,KNEE_VALGUS_MAX_RATIO:.12,TRUNK_SIDE_LEAN_MAX_DEG:10,VERTICAL_BOB_MAX_RATIO:.16,MIN_STANCE_WIDTH_RATIO:.55,MIN_REP_DURATION_MS:600,MAX_REP_DURATION_MS:5000,TOO_FAST_DURATION_MS:900};
export const HP09_ANALYSIS_MODE="mediapipe_hp09_monster_walk";
export const DEFAULT_HP09_REWARD_XP=30;
