export const CR01_INDEX = {
  LEFT_SHOULDER: 11, RIGHT_SHOULDER: 12,
  LEFT_ELBOW: 13, RIGHT_ELBOW: 14,
  LEFT_WRIST: 15, RIGHT_WRIST: 16,
  LEFT_HIP: 23, RIGHT_HIP: 24,
  LEFT_KNEE: 25, RIGHT_KNEE: 26,
  LEFT_ANKLE: 27, RIGHT_ANKLE: 28,
};

export const CR01_REQUIRED_LANDMARKS = Object.values(CR01_INDEX);
export const CR01_THRESHOLDS = {
  MIN_VISIBILITY: 0.45,
  HIP_LINE_MAX_RATIO: 0.10,
  KNEE_ANGLE_MIN_DEG: 155,
  ELBOW_ANGLE_MIN_DEG: 65,
  ELBOW_ANGLE_MAX_DEG: 120,
  BODY_INCLINE_MAX_DEG: 25,
  MAX_FRAME_GAP_MS: 1000,
};
export const CR01_ANALYSIS_MODE = "mediapipe_cr01_plank";
export const DEFAULT_CR01_REWARD_XP = 30;
