export const CR04_INDEX={LEFT_EAR:7,RIGHT_EAR:8,LEFT_SHOULDER:11,RIGHT_SHOULDER:12,LEFT_HIP:23,RIGHT_HIP:24,LEFT_KNEE:25,RIGHT_KNEE:26};
export const CR04_REQUIRED_LANDMARKS=Object.values(CR04_INDEX);
export const CR04_THRESHOLDS={MIN_VISIBILITY:.5,HOLD_DURATION_MS:6000,REST_DURATION_MS:1200,TRUNK_LEAN_MAX_DEG:10,SHOULDER_TILT_MAX_DEG:8,HIP_TILT_MAX_DEG:7,SWAY_MAX_RATIO:.08,MAX_FRAME_GAP_MS:1000};
export const CR04_ANALYSIS_MODE="mediapipe_cr04_seated_core_contraction";export const DEFAULT_CR04_REWARD_XP=30;
