import { F02_THRESHOLDS as T } from "./constants.js";
export function createBalanceSeriesSession(profile,config={}){
 const t=config.thresholds||T,target=Math.max(1,Number(config.targetReps)||profile.targetReps||1),targetMs=(profile.targetSeconds||0)*1000;
 let base=null,last=0,held=0,phase="calibrating",side=null,start=0,hold=0,reps=[],left=0,right=0,steps=0,sway=0,tilt=0,fast=0,tracking=0,ready=false,lastEvent={};
 const event=(k,now)=>{if(now-(lastEvent[k]??-Infinity)>t.EVENT_COOLDOWN_MS){lastEvent[k]=now;return true}return false};
 const summary=()=>({totalReps:profile.mode==="static"?(held>=targetMs?1:0):reps.length,targetReps:target,targetSeconds:profile.targetSeconds||null,heldMs:Math.min(targetMs,held),heldSeconds:Math.floor(Math.min(targetMs,held)/1000),leftReps:left,rightReps:right,validReps:reps.filter(r=>!r.issues.length).length+(profile.mode==="static"&&held>=targetMs?1:0),stepCount:steps,largeSwayCount:sway,tiltCount:tilt,tooFastCount:fast,trackingInterruptionCount:tracking,repRecords:reps.slice(),phase,completed:profile.mode==="static"?held>=targetMs:reps.length>=target});
 function processFrame(f){const now=f.timestamp||0,dt=Math.min(100,Math.max(0,now-last));last=now;if(!f.bodyReady){if(ready)tracking++;ready=false;return{summary:summary(),feedback:"請保持全身、雙手與雙腳完整入鏡"};}ready=true;
  if(!base){base={cx:f.centerX,cy:f.centerY,lx:f.leftAnkleX,rx:f.rightAnkleX,ly:f.leftAnkleY,ry:f.rightAnkleY,lwx:f.leftWristX,rwx:f.rightWristX};phase="ready";return{summary:summary(),feedback:"起始姿勢已建立，可以開始"};}
  const dx=(f.centerX-base.cx)/f.bodyScale,dy=(f.centerY-base.cy)/f.bodyScale,ankleDelta=Math.max(Math.abs(f.leftAnkleX-base.lx),Math.abs(f.rightAnkleX-base.rx),Math.abs(f.leftAnkleY-base.ly),Math.abs(f.rightAnkleY-base.ry))/f.bodyScale;
  const tilted=f.shoulderTiltDeg>t.STATIC_TILT_MAX_DEG||f.pelvisTiltDeg>t.STATIC_TILT_MAX_DEG;if(ankleDelta>t.STEP_ANKLE_DELTA_RATIO&&event("step",now))steps++;if(tilted&&event("tilt",now))tilt++;
  if(profile.mode==="static"){const stanceOk=profile.stance==="side"?f.ankleDepth<.30:profile.stance==="semi"?f.ankleDepth>=.12&&f.ankleDepth<.65:f.ankleDepth>=.35;const stable=Math.hypot(dx,dy)<=t.STATIC_SWAY_MAX&&!tilted&&ankleDelta<=t.STEP_ANKLE_DELTA_RATIO&&stanceOk;if(stable)held+=dt;else if(Math.hypot(dx,dy)>t.STATIC_SWAY_MAX&&event("sway",now))sway++;return{summary:summary(),feedback:!stanceOk?"請依動作說明調整雙腳位置":ankleDelta>t.STEP_ANKLE_DELTA_RATIO?"雙腳請保持原位":tilted?"保持肩膀與骨盆水平":stable?"很好，繼續穩定維持":"晃動較大，先站穩再繼續"};}
  let value=profile.mode==="shift"?dx:profile.direction==="forward"?Math.max(Math.abs(f.leftWristX-base.lwx),Math.abs(f.rightWristX-base.rwx))/f.bodyScale:Math.max(base.lwx-f.leftWristX,f.rightWristX-base.rwx)/f.bodyScale;
  if(phase==="ready"&&Math.abs(value)>=t.REACH_START_RATIO){phase="out";start=now;hold=0;side=value<0?"left":"right";}
  if(phase==="out"){if(Math.abs(value)>= (profile.mode==="shift"?t.SHIFT_TARGET_RATIO:t.REACH_TARGET_RATIO))hold+=dt;if(hold>=t.HOLD_MS)phase="returning";}
  if(phase==="returning"&&Math.abs(value)<=t.RETURN_RATIO){const durationMs=now-start,issues=[];if(ankleDelta>t.STEP_ANKLE_DELTA_RATIO)issues.push("step");if(tilted)issues.push("tilt");if(durationMs<t.MIN_REP_MS){issues.push("fast");fast++;}let rep=null;if(durationMs<=t.MAX_REP_MS){rep={side,durationMs,issues};reps.push(rep);if(side==="left")left++;else right++;}phase="ready";side=null;base={...base,cx:f.centerX,cy:f.centerY,lx:f.leftAnkleX,rx:f.rightAnkleX,ly:f.leftAnkleY,ry:f.rightAnkleY,lwx:f.leftWristX,rwx:f.rightWristX};return{summary:summary(),completedRep:rep,feedback:issues.length?"完成一次，請依提醒調整":"很好，位移與回位控制穩定"};}
  return{summary:summary(),feedback:ankleDelta>t.STEP_ANKLE_DELTA_RATIO?"雙腳不可跨步或移動":tilted?"肩膀與骨盆保持水平":phase==="out"?"繼續緩慢移動並短暫停留":phase==="returning"?"慢慢回到起始位置":"準備開始下一次"};
 }return{processFrame,getSummary:summary};
}
