export const CR02_INDEX = { NOSE:0, LEFT_EAR:7, RIGHT_EAR:8, LEFT_SHOULDER:11, RIGHT_SHOULDER:12, LEFT_HIP:23, RIGHT_HIP:24, LEFT_KNEE:25, RIGHT_KNEE:26 };
export const CR02_REQUIRED_LANDMARKS = Object.values(CR02_INDEX);
export const CR02_THRESHOLDS = { MIN_VISIBILITY:.45, RAISE_DELTA_MIN_DEG:16, RETURN_DELTA_MAX_DEG:7, NECK_ALIGNMENT_MIN_DEG:140, PELVIS_MOVEMENT_MAX_RATIO:.12, MIN_REP_DURATION_MS:900, MAX_REP_DURATION_MS:6000, MAX_FRAME_GAP_MS:1000 };
export const CR02_ANALYSIS_MODE = "mediapipe_cr02_crunch";
export const DEFAULT_CR02_REWARD_XP = 30;
