export const LE06_LANDMARK_INDEX={LEFT_SHOULDER:11,RIGHT_SHOULDER:12,LEFT_HIP:23,RIGHT_HIP:24,LEFT_KNEE:25,RIGHT_KNEE:26,LEFT_ANKLE:27,RIGHT_ANKLE:28};
const P=LE06_LANDMARK_INDEX;
export const LE06_REQUIRED_LANDMARKS=[P.LEFT_SHOULDER,P.RIGHT_SHOULDER,P.LEFT_HIP,P.RIGHT_HIP,P.LEFT_KNEE,P.RIGHT_KNEE,P.LEFT_ANKLE,P.RIGHT_ANKLE];
export const LE06_THRESHOLDS={MIN_VISIBILITY:.55,TARGET_DURATION_MS:30000,CALIBRATION_MS:1200,MODERATE_SWAY_RATIO:.035,LARGE_SWAY_RATIO:.065,TRUNK_LEAN_MAX_DEG:10,STEP_WIDTH_CHANGE_RATIO:.5,EVENT_COOLDOWN_MS:900,MAX_FRAME_GAP_MS:1200};
export const LE06_ANALYSIS_MODE="mediapipe_le06_balance";
export const DEFAULT_LE06_REWARD_XP=30;
