import{AD01_THRESHOLDS as T}from"./constants.js";
export function createBedRollingSession(c={}){
 const t=c.thresholds||T,target=Math.max(1,Number(c.targetPerSide)||t.TARGET_PER_SIDE);let baseShoulder=null,baseHip=null,phase="supine",sideStart=0,sideHold=0,rollDirection="right",last=0,left=0,right=0,valid=0,reps=[],sync=0,knee=0,fast=0,slow=0,incomplete=0,tracking=0,wasReady=false;
 const summary=()=>({leftReps:left,rightReps:right,totalReps:left+right,targetPerSide:target,targetReps:target*2,validReps:valid,shoulderHipSyncCount:sync,kneePositionCount:knee,tooFastCount:fast,tooSlowCount:slow,incompleteReturnCount:incomplete,trackingInterruptionCount:tracking,repRecords:reps,completed:left>=target&&right>=target});
 function processFrame(f){const now=f.timestamp||0,dt=Math.min(100,Math.max(0,now-last));last=now;if(!f.bodyReady){if(wasReady)tracking++;wasReady=false;return{summary:summary(),feedback:"請讓頭、肩、髖、膝與雙腳完整入鏡"};}wasReady=true;if(baseShoulder==null){baseShoulder=f.shoulderWidthRatio;baseHip=f.hipWidthRatio;}
 const sw=f.shoulderWidthRatio/baseShoulder,hw=f.hipWidthRatio/baseHip,side=sw<=t.SIDE_SHOULDER_WIDTH_RATIO&&hw<=t.SIDE_HIP_WIDTH_RATIO,returned=sw>=t.RETURN_WIDTH_RATIO&&hw>=t.RETURN_WIDTH_RATIO,syncDiff=Math.abs(sw-hw),bent=Math.max(f.leftKneeFlexionDeg||0,f.rightKneeFlexionDeg||0)>=t.KNEE_FLEXION_MIN_DEG&&Math.max(f.leftKneeFlexionDeg||0,f.rightKneeFlexionDeg||0)<=t.KNEE_FLEXION_MAX_DEG;
 if(phase==="supine"&&side){phase="side";sideStart=now;sideHold=0;rollDirection=f.noseOffset<0?"left":"right";}else if(phase==="side"){if(side)sideHold+=dt;if(returned&&sideHold>=t.SIDE_HOLD_MS){const duration=now-sideStart,direction=rollDirection,issues=[];if(syncDiff>t.SHOULDER_HIP_SYNC_MAX){issues.push("sync");sync++;}if(!bent){issues.push("knee");knee++;}if(duration<t.MIN_ROLL_MS){issues.push("fast");fast++;}if(duration>t.MAX_ROLL_MS){issues.push("slow");slow++;}if(direction==="left")left++;else right++;if(!issues.length)valid++;const rep={direction,durationMs:duration,issues};reps.push(rep);phase="supine";baseShoulder=baseShoulder*.9+f.shoulderWidthRatio*.1;baseHip=baseHip*.9+f.hipWidthRatio*.1;return{summary:summary(),completedRep:rep,feedback:issues.length?"完成一次，請依提醒調整":"肩膀與骨盆同步翻身很好"};}else if(!side&&!returned){incomplete++;phase="supine";}}
 const feedback=syncDiff>t.SHOULDER_HIP_SYNC_MAX?"肩膀與骨盆要一起轉動":!bent?"先屈曲一側膝蓋再帶動翻身":phase==="side"?"維持側躺後，慢慢回到仰躺":"屈曲一側膝蓋，肩與骨盆同步翻身";return{summary:summary(),feedback};}
 return{processFrame,getSummary:summary};
}
