export const CR07_INDEX={LEFT_SHOULDER:11,RIGHT_SHOULDER:12,LEFT_HIP:23,RIGHT_HIP:24,LEFT_KNEE:25,RIGHT_KNEE:26,LEFT_ANKLE:27,RIGHT_ANKLE:28};
export const CR07_REQUIRED_LANDMARKS=Object.values(CR07_INDEX);
export const CR07_THRESHOLDS={MIN_VISIBILITY:.45,SWAY_MIN_RATIO:.12,CENTER_MAX_RATIO:.055,EXCESSIVE_SWAY_RATIO:.38,KNEE_SEPARATION_CHANGE_MAX_RATIO:.16,SHOULDER_MOVE_MAX_RATIO:.07,HIP_TILT_MAX_DEG:18,MIN_REP_DURATION_MS:900,MAX_REP_DURATION_MS:6000,MAX_FRAME_GAP_MS:1000};
export const CR07_ANALYSIS_MODE="mediapipe_cr07_supine_knee_sway";export const DEFAULT_CR07_REWARD_XP=30;
