export const SH01_INDEX={LEFT_SHOULDER:11,RIGHT_SHOULDER:12,LEFT_ELBOW:13,RIGHT_ELBOW:14,LEFT_WRIST:15,RIGHT_WRIST:16,LEFT_HIP:23,RIGHT_HIP:24};
const P=SH01_INDEX;
export const SH01_REQUIRED_LANDMARKS=[P.LEFT_SHOULDER,P.RIGHT_SHOULDER,P.LEFT_ELBOW,P.RIGHT_ELBOW,P.LEFT_WRIST,P.RIGHT_WRIST,P.LEFT_HIP,P.RIGHT_HIP];
export const SH01_THRESHOLDS={MIN_VISIBILITY:.5,SWING_START_RATIO:.025,SWING_PEAK_RATIO:.045,RETURN_RATIO:.018,MIN_AMPLITUDE_RATIO:.035,MAX_AMPLITUDE_RATIO:.2,ARM_LIFT_MAX_DEG:25,TRUNK_FORWARD_MIN_DEG:15,TRUNK_FORWARD_MAX_DEG:65,SHRUG_MAX_RATIO:.06,MIN_CYCLE_MS:700,MAX_CYCLE_MS:5000,TOO_FAST_MS:1100,MAX_FRAME_GAP_MS:1200};
export const SH01_ANALYSIS_MODE="mediapipe_sh01_shoulder_pendulum";
export const DEFAULT_SH01_REWARD_XP=30;
