import { POSE_LANDMARK_INDEX } from "../../squatConstants.js";

export const KN03_REQUIRED_LANDMARKS = [
  POSE_LANDMARK_INDEX.LEFT_SHOULDER,
  POSE_LANDMARK_INDEX.RIGHT_SHOULDER,
  POSE_LANDMARK_INDEX.LEFT_HIP,
  POSE_LANDMARK_INDEX.RIGHT_HIP,
  POSE_LANDMARK_INDEX.LEFT_KNEE,
  POSE_LANDMARK_INDEX.RIGHT_KNEE,
  POSE_LANDMARK_INDEX.LEFT_ANKLE,
  POSE_LANDMARK_INDEX.RIGHT_ANKLE,
];

export const KN03_THRESHOLDS = {
  MIN_VISIBILITY: 0.55,
  NEUTRAL_KNEE_ANGLE_MAX_DEG: 110,
  REP_START_KNEE_ANGLE_MIN_DEG: 125,
  CANDIDATE_TOP_KNEE_ANGLE_MIN_DEG: 155,
  TARGET_EXTENSION_KNEE_ANGLE_MIN_DEG: 165,
  TRUNK_LEAN_MAX_DEG: 10,
  THIGH_LIFT_MAX_DEG: 12,
  NEUTRAL_CONFIRM_FRAMES: 3,
  TOP_CONFIRM_FRAMES: 2,
  MIN_REP_DURATION_MS: 650,
  MAX_REP_DURATION_MS: 6500,
  TOO_FAST_DURATION_MS: 1000,
  MAX_FRAME_GAP_MS: 1200,
  SIMULTANEOUS_EXTENSION_WINDOW_MS: 350,
};

export const KN03_SCORE_RULES = {
  BASE_SCORE: 100,
  MIN_SCORE: 0,
  MAX_SCORE: 100,
  INSUFFICIENT_EXTENSION_PENALTY: 8,
  EXCESSIVE_TRUNK_LEAN_PENALTY: 5,
  THIGH_LIFT_PENALTY: 5,
  RHYTHM_PENALTY: 4,
  TOO_FAST_PENALTY: 3,
  MISSING_REP_PENALTY: 2,
  GRADE_THRESHOLDS: [
    { min: 90, label: "Excellent" },
    { min: 75, label: "Good" },
    { min: 60, label: "Fair" },
    { min: 0, label: "Needs Practice" },
  ],
};

export const KN03_ANALYSIS_MODE = "mediapipe_kn03_seated_knee_extension";
export const DEFAULT_KN03_REWARD_XP = 30;
