import { LE05_THRESHOLDS } from "./constants.js";
import { evaluateSitToStandQuality } from "./quality.js";
export const LE05_STATE={SEATED:"seated",RISING:"rising",STANDING:"standing",LOWERING:"lowering"};
export function createSitToStandSession(config={}){const t=config.thresholds||LE05_THRESHOLDS,targetReps=Math.max(1,Number(config.targetReps)||10);let state=LE05_STATE.SEATED,reps=[],startedAt=null,standingAt=null,maxKneeAngle=0,maxTrunkLeanDeg=0,maxKneeAsymmetryDeg=0,kneeValgusSuspected=false,standConfirm=0,seatConfirm=0,lastValidAt=null,trackingInterruptionCount=0,interrupted=false;
function resetRep(){startedAt=null;standingAt=null;maxKneeAngle=0;maxTrunkLeanDeg=0;maxKneeAsymmetryDeg=0;kneeValgusSuspected=false;standConfirm=0;seatConfirm=0;}
function summary(){const c=x=>reps.filter(r=>r.issues.includes(x)).length,avg=f=>reps.length?Math.round(reps.reduce((a,r)=>a+r[f],0)/reps.length):null;return{totalReps:reps.length,targetReps,validReps:reps.filter(r=>r.qualityValid).length,qualityValidReps:reps.filter(r=>r.qualityValid).length,incompleteStandCount:c("incomplete_stand"),excessiveTrunkLeanCount:c("excessive_trunk_lean"),kneeValgusCount:c("knee_valgus"),asymmetryCount:c("asymmetry"),tooFastCount:c("too_fast"),fastDescentCount:c("fast_descent"),trackingInterruptionCount,repsWithTrackingGap:trackingInterruptionCount,averageMaxKneeAngle:avg("maxKneeAngle"),averageRepDuration:avg("durationMs"),state,repRecords:reps.slice(),completed:reps.length>=targetReps};}
function processFrame({timestamp,averageKneeAngle,trunkLeanDeg,kneeAsymmetryDeg,kneeValgus,bodyReady}){if(!bodyReady||averageKneeAngle==null){if(state!==LE05_STATE.SEATED&&!interrupted)trackingInterruptionCount++;interrupted=true;return{repCompleted:false,completedRep:null,summary:summary()};}interrupted=false;if(lastValidAt!=null&&state!==LE05_STATE.SEATED&&timestamp-lastValidAt>t.MAX_FRAME_GAP_MS){state=LE05_STATE.SEATED;resetRep();}lastValidAt=timestamp;
if(state===LE05_STATE.SEATED&&averageKneeAngle>=t.RISE_START_KNEE_ANGLE_MIN_DEG){state=LE05_STATE.RISING;startedAt=timestamp;maxKneeAngle=averageKneeAngle;}
if(state!==LE05_STATE.SEATED){maxKneeAngle=Math.max(maxKneeAngle,averageKneeAngle);maxTrunkLeanDeg=Math.max(maxTrunkLeanDeg,trunkLeanDeg||0);maxKneeAsymmetryDeg=Math.max(maxKneeAsymmetryDeg,kneeAsymmetryDeg||0);kneeValgusSuspected=kneeValgusSuspected||!!kneeValgus;}
if(state===LE05_STATE.RISING){if(averageKneeAngle>=t.CANDIDATE_STANDING_KNEE_ANGLE_MIN_DEG){standConfirm++;if(standConfirm>=t.STANDING_CONFIRM_FRAMES){state=LE05_STATE.STANDING;standingAt=timestamp;}}else standConfirm=0;}
else if(state===LE05_STATE.STANDING&&averageKneeAngle<t.CANDIDATE_STANDING_KNEE_ANGLE_MIN_DEG-8)state=LE05_STATE.LOWERING;
else if(state===LE05_STATE.LOWERING){if(averageKneeAngle>=t.CANDIDATE_STANDING_KNEE_ANGLE_MIN_DEG){state=LE05_STATE.STANDING;seatConfirm=0;}else if(averageKneeAngle<=t.SEATED_KNEE_ANGLE_MAX_DEG){seatConfirm++;if(seatConfirm>=t.SEATED_CONFIRM_FRAMES){const durationMs=timestamp-startedAt,descentDurationMs=standingAt==null?durationMs:timestamp-standingAt;let completedRep=null;if(durationMs<=t.MAX_REP_DURATION_MS){const q=evaluateSitToStandQuality({maxKneeAngle,maxTrunkLeanDeg,maxKneeAsymmetryDeg,kneeValgusSuspected,durationMs,descentDurationMs},t);completedRep={repNumber:reps.length+1,startedAt,completedAt:timestamp,durationMs,descentDurationMs,maxKneeAngle,maxTrunkLeanDeg,maxKneeAsymmetryDeg,kneeValgusSuspected,qualityValid:q.valid,issues:q.issues};reps.push(completedRep);}state=LE05_STATE.SEATED;resetRep();return{repCompleted:!!completedRep,completedRep,summary:summary()};}}else seatConfirm=0;}
return{repCompleted:false,completedRep:null,summary:summary()};}
function reset(){state=LE05_STATE.SEATED;reps=[];trackingInterruptionCount=0;interrupted=false;lastValidAt=null;resetRep();}
return{processFrame,getSummary:summary,reset};}
