export const LE07_INDEX={LEFT_SHOULDER:11,RIGHT_SHOULDER:12,LEFT_HIP:23,RIGHT_HIP:24,LEFT_KNEE:25,RIGHT_KNEE:26,LEFT_ANKLE:27,RIGHT_ANKLE:28,LEFT_HEEL:29,RIGHT_HEEL:30,LEFT_FOOT:31,RIGHT_FOOT:32};
const P=LE07_INDEX;
export const LE07_REQUIRED_LANDMARKS=[P.LEFT_SHOULDER,P.RIGHT_SHOULDER,P.LEFT_HIP,P.RIGHT_HIP,P.LEFT_KNEE,P.RIGHT_KNEE,P.LEFT_ANKLE,P.RIGHT_ANKLE,P.LEFT_HEEL,P.RIGHT_HEEL,P.LEFT_FOOT,P.RIGHT_FOOT];
export const LE07_THRESHOLDS={MIN_VISIBILITY:.5,REP_START_RISE_RATIO:.025,TOP_RISE_RATIO:.05,TARGET_RISE_RATIO:.055,RETURN_RISE_RATIO:.018,HEEL_ASYMMETRY_MAX_RATIO:.025,KNEE_EXTENSION_MIN_DEG:160,TRUNK_LEAN_MAX_DEG:12,TOP_CONFIRM_FRAMES:2,RETURN_CONFIRM_FRAMES:3,MIN_REP_DURATION_MS:800,MAX_REP_DURATION_MS:6000,TOO_FAST_DURATION_MS:1400,MAX_FRAME_GAP_MS:1200};
export const LE07_ANALYSIS_MODE="mediapipe_le07_calf_raise";
export const DEFAULT_LE07_REWARD_XP=30;
